### ISSUE TITLE
Feature Request: Add the option `smtp-passwordeval`

### ISSUE THREAD

**Issue by doronbehar** [wking/rss2email#110]
Just like many other command line applications and mail clients, usually there is an option available that enables specifying passwords in configuration files not in plain-text, but via an external command's output. Usually that is being used for commands like `gpg` that decrypt a file and print it's content and this content is the password.

I think `rss2email` should have such option as well.

Best regards.

**Comment by Ekleog** [comment]
Hello,

This repository has been deprecated for a few years now, and has been replaced by https://github.com/rss2email/rss2email .

If this issue is still relevant to you, and not fixed with v3.12.2, could you please reopen the issue there?

Cheers,
  Leo
