### ISSUE TITLE
How would you like to accept zsh completion?

### ISSUE THREAD

**Issue by doronbehar** [wking/rss2email#111]
I've wrote a ZSH completion for `r2e` and I'd like to contribute it to this project. It even allows to complete feeds for the `delete` sub-command.

**Comment by eqyiel** [comment]
Maybe open a PR here: https://github.com/rss2email/rss2email

More info:
https://github.com/wking/rss2email/issues/105

**Comment by doronbehar** [comment]
Thanks, closing in favor of https://github.com/rss2email/rss2email/pull/24 .
