### ISSUE TITLE
grouping of feeds

### ISSUE THREAD

**Issue by rickysarraf** [wking/rss2email#55]
I have many feeds, around 30 - 40. With rss2email, all get added straight. But there is no categorization.

I'd like to fetch a group of feeds at a more frequent interval, than others which I don't find polling once a day. How can this be achieved with rss2email ?

**Comment by 0xf10e** [comment]
The `run_parser.add_argument(
        'index', nargs='*', …` part in [rss2email/main.py](https://github.com/wking/rss2email/blob/master/rss2email/main.py) makes the run command accept any number of feed IDs.

Just add the IDs of feeds you want to query more frequently to a additionaly scheduled (via cron or whatever) `r2e run …`.

**Comment by rickysarraf** [comment]
Thanks. That helped. Similar content is also present in the manpage. I should have RTFMed..
