### ISSUE TITLE
Can't get r2e to work in Amazon EC2 instance

### ISSUE THREAD

**Issue by ChrisAndrew** [wking/rss2email#58]
Hi! 

I tried to configure r2e to send me and my teammates productions crashs looged in a feed running in an Amazon E2C instance, but no emails is received, no error message is returned and i am not able to find a log to troubleshoot the problem.

I am using a gmail SMTP account  and have the same config running successfuly in a local staging server.

I don't think this is an issue in r2e, but maybe a common misstep some of you guys can point out?

I hope you can help me in this one. Thanks in advance!

**Comment by ChrisAndrew** [comment]
Hi again!

We are running rss2email over Acralyzer feed. What I have noticed is that some of the early entries in the feed are sent if we reset rss2email, but stop at some point to never send another one.

In the mean time I've setup slack.com to notify us and it is able to do so.

What am I missing?

**Comment by chrisandrewcl** [comment]
If someone stumble on something like that some day:

.../_design/acra-storage/_list/rss/recent-items?**descending=true** is what resolved our issue with Acralyzer feed sending some old entries and not the new ones.
