### ISSUE TITLE
feed identifier in mail headers

### ISSUE THREAD

**Issue by jwilk** [wking/rss2email#61]
I'd love if rss2email put the feed identifier (that is, the name you put between square brackets in the configuration file) somewhere into mail headers.
This would allow me to greatly simplify my mail filters.

**Comment by brycied00d** [comment]
Why not use the `X-RSS-Feed` header that's already present?

**Comment by jwilk** [comment]
Feed URL, unlike feed identifier, is not something I control.
Worse, the URL can change behind my back, thanks to permanent redirects.

**Comment by brycied00d** [comment]
That's true. I'm simply pointing it out as a "now solution" rather than waiting for it to be implemented+merged. For that matter I can't recall the last time a feed returned a 301, but it is a technical possibility.

Try https://github.com/wking/rss2email/commit/2a3d0fef1ba34ec1b35b53fe91ff8fcc818c6fa8.diff and see if that works for you.

**Comment by wking** [comment]
On Wed, Nov 18, 2015 at 10:49:19AM -0800, Bryce Chidester wrote:
> Try
> https://github.com/wking/rss2email/commit/2a3d0fef1ba34ec1b35b53fe91ff8fcc818c6fa8.diff
> and see if that works for you.

This approach looks reasonable.  You can also set an arbitrary
additional header on a per-feed basis [1].

[1]: https://github.com/wking/rss2email/blob/v3.9/rss2email/config.py#L106-L108

**Comment by jwilk** [comment]
2a3d0fef1ba3 works for me. Thanks!

**Comment by Ekleog** [comment]
Hello,

This repository has been deprecated for a few years now, and has been replaced by https://github.com/rss2email/rss2email .

If this issue is still relevant to you, and not fixed with v3.12.2, could you please reopen the issue there?

Cheers,
  Leo

**Comment by jwilk** [comment]
I'm happy with <https://github.com/rss2email/rss2email/pull/122>, so let's close this.
