### ISSUE TITLE
Option to fetch whole referenced article

### ISSUE THREAD

**Issue by madduck** [wking/rss2email#70]
Most RSS feeds only include a teaser and not the whole article, which is a shame as I'd love to read the whole article right there.

How about an option to make `r2e` go out and fetch the referenced page?

Bonus points for a per-feed regexp to turn the reference URL (which usually just opens page 1) into e.g. the print version (all on one page).

Thanks,
martin

**Comment by Ekleog** [comment]
Hello,

This repository has been deprecated for a few years now, and has been replaced by https://github.com/rss2email/rss2email .

If this issue is still relevant to you, and not fixed with v3.12.2, could you please reopen the issue there?

Cheers,
  Leo

**Comment by madduck** [comment]
This has moved to https://github.com/rss2email/rss2email/issues/90
