### ISSUE TITLE
Is this fork of rss2email abandoned?

### ISSUE THREAD

**Issue by RalphCorderoy** [wking/rss2email#93]
Hi, Arch Linux uses this as its upstream rss2email.  I expect other distros do too.  Is activity likely to pick up here?  I've an issue with ~/.rss2email/feeds.dat being non-JSON pickled data that won't load after upgrading to this version in Arch and I'm looking for the best place to report the problem.  If time's too short to work on rss2email any more then can I suggest looking at https://github.com/wking/rss2email/network and seeing if any fork stands out as a possible new keeper of the flame, e.g. @sr?  Thanks.

**Comment by Lenbok** [comment]
See #97, perhaps worth forking to an organisation and inviting contributors.

**Comment by 0xf10e** [comment]
There's https://github.com/rss2email/rss2email now, so I guess this one can be closed.

**Comment by 0xf10e** [comment]
Fixed together with #97, isn't it?

**Comment by Ekleog** [comment]
This has been done, and the development has moved over to https://github.com/rss2email/rss2email indeed :)

**Comment by Ekleog** [comment]
This has been done, and the development has moved over to https://github.com/rss2email/rss2email indeed :) we tried to integrate most of the code that had been developed outside of this repo, too, for 3.11, but if we missed something, feel free to send a PR there!

**Comment by RalphCorderoy** [comment]
The author of this repo has anointed a new carrier of the rss2email flame: https://github.com/wking/rss2email/issues/97#issuecomment-328346160

It would be nice if this repo's README stated that at the start for newcomers, but I've got my answer so closing this issue.
