### ISSUE TITLE
auth info in url 

### ISSUE THREAD

**Issue by 2Belette** [wking/rss2email#96]
Hi,
I second this https://github.com/wking/rss2email/issues/80
I made lot of test and it is not supporting on the version rss2email 3.9

Any idea of the reason ? anything we can take a look on python code to improve this ? (don't want to roll back to v2.7 which is actually supporting it..)

**Comment by Ekleog** [comment]
Hello,

This repository has been deprecated for a few years now, and has been replaced by https://github.com/rss2email/rss2email .

If this issue is still relevant to you, and not fixed with v3.12.2, could you please reopen the issue there?

Cheers,
  Leo
